// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(Parcial2Context))]
    [Migration("20201113034313_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Pago", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(10)");

                    b.Property<string>("PersonaIdentificacion")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(12)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(16)");

                    b.HasKey("Codigo");

                    b.HasIndex("PersonaIdentificacion");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Entity.Persona", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Departamento")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Pais")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Identificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Entity.Pago", b =>
                {
                    b.HasOne("Entity.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaIdentificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
